### PR TITLE
Create imageTag.html

### PR DESCRIPTION
**Pull request by vikasjainn**
I am attaching a HTML file an image tag for hacktoberfest 2022 please pull it.

### CODE REVIEW

**Review by ankit0313 — APPROVED** [review]

**Comment by ankit0313** [comment]
Would be great if you could star the repository. Thanks

**Comment by vikasjainn** [comment]
Thanks for merge of my pull request. I am contributing some more request.
please merge that too. I have starred the repo also.

**Comment by ankit0313** [comment]
Definitely will do but try to contribute content other than that present in the repository . Thanks

**Comment by ankit0313** [comment]
Also it will be great if you star the repository if you haven't already as that'll help others also contribute in the same

**Comment by vikasjainn** [comment]
Done I have marked it starred. Please approve my more requests.

**Pull request merged**
